### ISSUE TITLE
No applicable method exists in type 

### ISSUE THREAD

**Issue by elvogel** [microsoft/RulesEngine#46] opened 2020-08-31 22:48 UTC
Same project, new issues. This time I've got the source code and the project linked to my solution, so I'm using everything out of the master branch. 

My rule:
```json
[
  {
    "WorkflowName": "ConsItemPricePurchEntity",
    "Rules": [
      {
        "RuleName": "VendorPartyNumberExists",
        "SuccessEvent": "10",
        "WarningMessage": "Vendor party number does not exist in Dynamics",
        "ErrorType": "Warning",
        "RuleExpressionType": "LambdaExpression",
        "Expression": "utils.ElementNameExists(input1.ELEMENTNAME)"
      },
      {
        "RuleName": "BuildingTypeIdExists",
        "SuccessEvent": "15",
        "WarningMessage": "BuildingTypeId doesn't exist in Dynamics",
        "ErrorType": "Warning",
        "RuleExpressionType": "LambdaExpression",
        "Expression": "utils.BuildingTypeIdExists(input1.BUILDINGTYPEID)"
      }
    ]
  }
]
```

```csharp
results = engine.ExecuteRule(rule.WorkflowName,
    new RuleParameter(nameof(input1),input1),
    new RuleParameter(nameof(utils),utils));
```
I get this output for the rules:
`No applicable method 'ElementNameExists' exists in type 'Utils'`
`No applicable method 'BuildingTypeIdExists' exists in type 'Utils'`

I'm getting this whether I wrap everything in `RuleParameter` or not. I am, however, getting more consistent errors by making sure my input object is the first parameter. 

The methods are there...

![image](https://user-images.githubusercontent.com/2071112/91775977-8077ca00-ebba-11ea-867f-c86dafbc2d01.png)

**Comment by abbasc52** [comment] 2020-09-01 04:23
Potential duplicate of #39 
You can try the steps mentioned here - https://github.com/microsoft/RulesEngine/issues/39#issuecomment-678893995

**Comment by elvogel** [comment] 2020-09-01 05:04
I tried a couple of variations of rule modifications:

`utils.ElementNameExists((string)(input1.ELEMENTNAME)) == true`  and `(utils.ElementNameExists((string)(input1.ELEMENTNAME))) == true`

both give me this error: `'.' or '(' or string literal expected`

**Comment by elvogel** [comment] 2020-09-01 05:32
I have success! here's what my rules look like:

`utils.ElementNameExists(input1.ELEMENTNAME) == true`
`utils.BuildingTypeIdExists(input1.BUILDINGTYPEID) == true`

The big difference here lies in how you construct the engine and pass in the parameters. Here's what works:

```csharp
            engine = new global::RulesEngine.RulesEngine(workflowRules.ToArray(), log,new ReSettings()
            {
                //CustomTypes = new []{typeof(Utils)}
            });
```
```csharp
                            results = engine.ExecuteRule(rule.WorkflowName, 
                            new RuleParameter(nameof(input1),input1),
                            new RuleParameter(nameof(utils), utils));
```

**Comment by abbasc52** [comment] 2020-09-01 06:39
@elvogel  good to hear that! We will take this up and add it in documentation. I will close this issue since you seemed to have resolved the issue.

**Closed by abbasc52** 2020-09-01 06:39 UTC
