### ISSUE TITLE
why not support regular expressions ?

### ISSUE THREAD

**Issue by leonliuxu** [microsoft/RulesEngine#8] opened 2020-04-12 14:47 UTC
I wanna use this library in my project, but I found Lambda expression not support regular expression ?
Is there any suggestion for me ? 

Thanks a lot

**Comment by abbasc52** [comment] 2020-04-13 07:54
@leonliuxu  Could you provide an example of your use-case?
We do provide users an ability to inject their custom classes on their own 
```
var reSettings = new ReSettings{
	CustomTypes = new Type[] {MyCustomClass}
}

var bre = new BusinessRuleEngine(workflows, logger, reSettings)
```
You can add Regular Expression class or even your own custom classes this way. Only catch is when creating a new object in lambda expression you need to skip 'new' keyword.

E.g.  when using ` new Regex() ` just use `Regex()` in lambda expression.

Let me know if this solves your issue

**Comment by abbasc52** [comment] 2020-05-12 07:58
Closing this issue as we did not get any reply.
 @leonliuxu feel free to reopen this issue if you feel the issue is not closed

**Closed by abbasc52** 2020-05-12 07:58 UTC
Labels: question, waiting for op
